---
title: 'A1 Task 3: Text wrangling and analysis'
subtitle: 'Name of the Wind by Patrick Rofus'
author: "Laurel Wee"
date: "2/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytext)
library(textdata)
library(pdftools)
library(ggwordcloud)
library(here)
library(wordstonumbers)
library(textclean)
```

```{r, cache = TRUE}
kvothe_text <- pdf_text(here("data","the-name-of-the-wind.pdf"))
```


```{r}
kvothe_tidy <- data.frame(kvothe_text) %>% 
  slice(-(1:16)) %>% 
  mutate(text_full = str_split(kvothe_text, pattern = '\\n')) %>% 
  unnest(text_full) %>% 
  mutate(text_full = str_trim(text_full)) 
```

```{r}
kvothe_df <- kvothe_tidy %>% 
  mutate(chapter = case_when(
    str_detect(text_full, "CHAPTER") ~ text_full,
    TRUE ~ NA_character_
  )) %>% 
  fill(chapter) %>% 
  separate(col = chapter, into = c("ch", "no"), sep = " ") %>% 
  select(-kvothe_text) #%>% 
 # mgsub(no, replace_number(seq_len(1:92)))
```
```{r}
kvothe_tokens <- kvothe_df %>% 
  unnest_tokens(word, text_full)
```

```{r}
kvothe_wordcount <- kvothe_tokens %>% 
  count(no, word) 

kvothe_nostop_wordcount <- kvothe_tokens %>% 
  anti_join(stop_words)%>% 
  count(no, word)

top_5_words <- kvothe_nostop_wordcount %>% 
  group_by(no) %>% 
  arrange(-n) %>% 
  slice(1:5)
```
```{r}
#ggplot(data = top_5_words, aes(x = word, y = n)) +
 # geom_col(fill = "blue") +
  #facet_wrap(~no, scales = "free") +
  #coord_flip()
```
```{r}
top_100 <- kvothe_tokens %>% 
  anti_join(stop_words) %>% 
  ungroup() %>% 
  count(word) %>% 
  arrange(-n) %>% 
  filter(word != "patrick" & word != "rothfuss") %>% 
  slice(1:100)
```
### Sentiment analysis with afinn: 

First, bind words in `hobbit_nonstop_words` to `afinn` lexicon:
```{r}
kvothe_afinn <- kvothe_nonstop_words %>% 
  inner_join(get_sentiments("afinn"))
```

Let's find some counts (by sentiment ranking):
```{r}
afinn_counts <-kvothe_afinn %>% 
  count(no, value)

# Plot them: 
ggplot(data = afinn_counts, aes(x = value, y = n)) +
  geom_col() +
  facet_wrap(~no)

# Find the mean afinn score by chapter: 
afinn_means <- kvothe_afinn %>% 
  group_by(no) %>% 
  summarize(mean_afinn = mean(value))

ggplot(data = afinn_means, 
       aes(x = fct_rev(as.factor(chapter)), 
           y = mean_afinn)) +
  geom_col() +
  coord_flip()
```

### Now with NRC lexicon

Recall, this assigns words to sentiment bins. Let's bind our hobbit data to the NRC lexicon: 

```{r}
kvothe_nrc <- kvothe_nonstop_words %>% 
  inner_join(get_sentiments("nrc"))
```
Let's find the count of words by chapter and sentiment bin: 

```{r}
kvothe_nrc_counts <- kvothe_nrc %>% 
  count(no, sentiment)


ggplot(data = kvothe_nrc_counts, aes(x = sentiment, y = n)) +
  geom_col() +
  facet_wrap(~chapter) +
  coord_flip()
```
